const pid = (i: number) => `pub-${String(i).padStart(3, "0")}`;
const aid = (i: number) => `agent-${String(i).padStart(3, "0")}`;
const tid = (i: number) => `team-${String(i).padStart(3, "0")}`;

export const mockPublishers = [
  {
    id: pid(1),
    slug: "starchild-labs",
    displayName: "Starchild Labs",
    description: "Vibe-coding agents that help DEX builders ship features 10x faster. Born from the intersection of AI and DeFi.",
    isVerified: true,
    isEcosystemPartner: true,
    avatarUrl: null,
    websiteUrl: "https://starchild.ai",
    twitterHandle: "StarchildAI",
    githubOrg: "starchild-labs",
  },
  {
    id: pid(2),
    slug: "orderly-core",
    displayName: "Orderly Core",
    description: "Official agents from the Orderly Network team. Protocol-level infrastructure and tooling for the Orderly ecosystem.",
    isVerified: true,
    isEcosystemPartner: true,
    avatarUrl: null,
    websiteUrl: "https://orderly.network",
    twitterHandle: "OrderlyNetwork",
    githubOrg: "OrderlyNetwork",
  },
  {
    id: pid(3),
    slug: "woo-labs",
    displayName: "WOO Labs",
    description: "Institutional-grade trading and liquidity agents from the WOO ecosystem.",
    isVerified: true,
    isEcosystemPartner: true,
    avatarUrl: null,
    websiteUrl: "https://woo.org",
    twitterHandle: "WOOnetwork",
    githubOrg: null,
  },
  {
    id: pid(4),
    slug: "defi-dispatch",
    displayName: "DeFi Dispatch",
    description: "Community-driven social and analytics agents. Making on-chain data accessible to everyone.",
    isVerified: true,
    isEcosystemPartner: false,
    avatarUrl: null,
    websiteUrl: null,
    twitterHandle: "DeFiDispatch",
    githubOrg: "defi-dispatch",
  },
  {
    id: pid(5),
    slug: "perp-wizard",
    displayName: "PerpWizard",
    description: "Solo builder crafting best-in-class perpetual trading automation. Battle-tested strategies for Orderly perps.",
    isVerified: true,
    isEcosystemPartner: false,
    avatarUrl: null,
    websiteUrl: null,
    twitterHandle: null,
    githubOrg: "perpwizard",
  },
  {
    id: pid(6),
    slug: "chain-sentinel",
    displayName: "Chain Sentinel",
    description: "Infrastructure monitoring and alerting agents for DeFi protocols. Keep your systems healthy 24/7.",
    isVerified: false,
    isEcosystemPartner: false,
    avatarUrl: null,
    websiteUrl: null,
    twitterHandle: "ChainSentinel",
    githubOrg: null,
  },
  {
    id: pid(7),
    slug: "neural-trade",
    displayName: "NeuralTrade",
    description: "ML-powered trading signal agents with backtested strategies across multiple timeframes.",
    isVerified: true,
    isEcosystemPartner: false,
    avatarUrl: null,
    websiteUrl: "https://neuraltrade.xyz",
    twitterHandle: null,
    githubOrg: null,
  },
  {
    id: pid(8),
    slug: "orderly-community",
    displayName: "Orderly Community",
    description: "Open-source agents contributed by independent builders in the Orderly ecosystem.",
    isVerified: false,
    isEcosystemPartner: false,
    avatarUrl: null,
    websiteUrl: null,
    twitterHandle: null,
    githubOrg: null,
  },
] as const;

export type MockPublisher = (typeof mockPublishers)[number];

export const mockAgents = [
  {
    id: aid(1),
    slug: "graduation-sniper",
    name: "Graduation Sniper",
    description: "Detects tokens graduating from bonding curves to DEX pools and executes instant snipe trades with configurable slippage and position sizing.",
    longDescription: "## Overview\n\nThe Graduation Sniper monitors bonding curve contracts across supported chains and instantly detects when tokens graduate to full DEX trading. It executes precision trades within the same block, giving you first-mover advantage.\n\n## Features\n\n- Real-time bonding curve monitoring\n- Sub-second execution on graduation events\n- Configurable max slippage and position size\n- Multi-chain support (Arbitrum, Optimism, Base)\n- Risk management with automatic stop-loss",
    division: "trading",
    runtime: "skill" as const,
    riskLevel: "degen" as const,
    status: "approved",
    iconEmoji: "🎯",
    version: "1.2.0",
    tags: ["sniper", "graduation", "bonding-curve", "degen"],
    supportedChains: ["arbitrum", "optimism", "base"],
    brokerCompatibility: "all",
    sourceRepoUrl: "https://github.com/perpwizard/graduation-sniper",
    mcpServerUrl: null,
    skillFileUrl: "/agents/trading/graduation-sniper/SKILL.md",
    starCount: 847,
    installCount: 2340,
    activeInstances: 156,
    configSchema: { maxSlippage: "number (0.01-0.5)", positionSize: "number (USD)", chains: "string[]" },
    publisherId: pid(5),
  },
  {
    id: aid(2),
    slug: "orderbook-analyst",
    name: "Orderbook Analyst",
    description: "Real-time orderbook depth analysis with liquidity heatmaps, whale detection, and spread monitoring across all Orderly pairs.",
    longDescription: "## Overview\n\nOrderbook Analyst provides deep visibility into market microstructure across every Orderly-powered DEX. It surfaces actionable insights from raw orderbook data.\n\n## Capabilities\n\n- Live orderbook depth visualization\n- Whale order detection (>$50k)\n- Bid-ask spread tracking with alerts\n- Liquidity shift notifications\n- Historical depth snapshots",
    division: "analytics",
    runtime: "mcp" as const,
    riskLevel: "low" as const,
    status: "approved",
    iconEmoji: "📊",
    version: "2.0.1",
    tags: ["orderbook", "analytics", "liquidity", "whales"],
    supportedChains: ["all"],
    brokerCompatibility: "all",
    sourceRepoUrl: "https://github.com/OrderlyNetwork/orderbook-analyst",
    mcpServerUrl: "https://mcp.orderly.network/orderbook-analyst",
    skillFileUrl: null,
    starCount: 1203,
    installCount: 3890,
    activeInstances: 412,
    configSchema: null,
    publisherId: pid(2),
  },
  {
    id: aid(3),
    slug: "dex-vibe-coder",
    name: "DEX Vibe Coder",
    description: "AI pair programmer that understands Orderly SDK patterns. Generates trading UI components, hooks, and integrations from natural language.",
    longDescription: null,
    division: "starchild",
    runtime: "skill" as const,
    riskLevel: "low" as const,
    status: "approved",
    iconEmoji: "✨",
    version: "3.1.0",
    tags: ["vibe-coding", "dx", "components", "sdk"],
    supportedChains: ["all"],
    brokerCompatibility: "all",
    sourceRepoUrl: "https://github.com/starchild-labs/dex-vibe-coder",
    mcpServerUrl: null,
    skillFileUrl: "/agents/starchild/dex-vibe-coder/SKILL.md",
    starCount: 2156,
    installCount: 5670,
    activeInstances: 890,
    configSchema: null,
    publisherId: pid(1),
  },
  {
    id: aid(4),
    slug: "perp-grid-bot",
    name: "Perp Grid Bot",
    description: "Automated grid trading strategy for Orderly perpetual markets with dynamic range adjustment based on volatility.",
    longDescription: null,
    division: "trading",
    runtime: "hosted" as const,
    riskLevel: "high" as const,
    status: "approved",
    iconEmoji: "📈",
    version: "1.0.0",
    tags: ["grid-trading", "perps", "automation"],
    supportedChains: ["arbitrum"],
    brokerCompatibility: "all",
    sourceRepoUrl: null,
    mcpServerUrl: null,
    skillFileUrl: null,
    starCount: 634,
    installCount: 1120,
    activeInstances: 0,
    configSchema: null,
    publisherId: pid(7),
  },
  {
    id: aid(5),
    slug: "social-sentiment",
    name: "Social Sentinel",
    description: "Aggregates and scores sentiment from Twitter, Discord, and Telegram for tokens trading on Orderly-powered DEXes.",
    longDescription: null,
    division: "social",
    runtime: "mcp" as const,
    riskLevel: "low" as const,
    status: "approved",
    iconEmoji: "📡",
    version: "1.4.2",
    tags: ["sentiment", "social", "twitter", "signals"],
    supportedChains: ["all"],
    brokerCompatibility: "all",
    sourceRepoUrl: "https://github.com/defi-dispatch/social-sentinel",
    mcpServerUrl: "https://mcp.defidispatch.io/sentiment",
    skillFileUrl: null,
    starCount: 956,
    installCount: 2780,
    activeInstances: 334,
    configSchema: null,
    publisherId: pid(4),
  },
  {
    id: aid(6),
    slug: "fee-optimizer",
    name: "Fee Optimizer",
    description: "Analyzes trading patterns across Orderly brokers and routes orders to minimize fees. Includes rebate tracking and fee tier analysis.",
    longDescription: null,
    division: "infra",
    runtime: "skill" as const,
    riskLevel: "low" as const,
    status: "approved",
    iconEmoji: "⚡",
    version: "2.1.0",
    tags: ["fees", "optimization", "routing"],
    supportedChains: ["all"],
    brokerCompatibility: "all",
    sourceRepoUrl: "https://github.com/OrderlyNetwork/fee-optimizer",
    mcpServerUrl: null,
    skillFileUrl: "/agents/infra/fee-optimizer/SKILL.md",
    starCount: 1567,
    installCount: 4230,
    activeInstances: 678,
    configSchema: null,
    publisherId: pid(2),
  },
  {
    id: aid(7),
    slug: "woo-liquidity-bridge",
    name: "WOO Liquidity Bridge",
    description: "Bridges deep liquidity from WOO Network into Orderly-powered DEXes. Ensures tight spreads and minimal slippage on large orders.",
    longDescription: null,
    division: "infra",
    runtime: "mcp" as const,
    riskLevel: "medium" as const,
    status: "approved",
    iconEmoji: "🌊",
    version: "1.3.0",
    tags: ["liquidity", "bridge", "woo", "spreads"],
    supportedChains: ["arbitrum", "optimism"],
    brokerCompatibility: "all",
    sourceRepoUrl: null,
    mcpServerUrl: "https://mcp.woo.org/liquidity-bridge",
    skillFileUrl: null,
    starCount: 723,
    installCount: 1890,
    activeInstances: 245,
    configSchema: null,
    publisherId: pid(3),
  },
  {
    id: aid(8),
    slug: "portfolio-rebalancer",
    name: "Portfolio Rebalancer",
    description: "Automatically rebalances multi-asset portfolios on Orderly with customizable allocation targets and drift thresholds.",
    longDescription: null,
    division: "trading",
    runtime: "skill" as const,
    riskLevel: "medium" as const,
    status: "approved",
    iconEmoji: "⚖️",
    version: "1.1.0",
    tags: ["portfolio", "rebalance", "automation"],
    supportedChains: ["arbitrum"],
    brokerCompatibility: "all",
    sourceRepoUrl: "https://github.com/perpwizard/portfolio-rebalancer",
    mcpServerUrl: null,
    skillFileUrl: "/agents/trading/portfolio-rebalancer/SKILL.md",
    starCount: 445,
    installCount: 890,
    activeInstances: 112,
    configSchema: null,
    publisherId: pid(5),
  },
  {
    id: aid(9),
    slug: "alert-engine",
    name: "Alert Engine",
    description: "Configurable price, volume, and on-chain event alerts delivered via webhooks, Telegram, or Discord for Orderly markets.",
    longDescription: null,
    division: "analytics",
    runtime: "mcp" as const,
    riskLevel: "low" as const,
    status: "approved",
    iconEmoji: "🔔",
    version: "2.3.0",
    tags: ["alerts", "notifications", "monitoring"],
    supportedChains: ["all"],
    brokerCompatibility: "all",
    sourceRepoUrl: "https://github.com/chain-sentinel/alert-engine",
    mcpServerUrl: "https://mcp.chainsentinel.io/alerts",
    skillFileUrl: null,
    starCount: 1890,
    installCount: 5120,
    activeInstances: 789,
    configSchema: null,
    publisherId: pid(6),
  },
  {
    id: aid(10),
    slug: "ui-kit-generator",
    name: "UI Kit Generator",
    description: "Generates production-ready React trading UI components styled for your DEX brand. Includes orderbook, chart, and trade panel widgets.",
    longDescription: null,
    division: "building",
    runtime: "skill" as const,
    riskLevel: "low" as const,
    status: "approved",
    iconEmoji: "🎨",
    version: "1.5.0",
    tags: ["ui", "components", "react", "widgets"],
    supportedChains: ["all"],
    brokerCompatibility: "all",
    sourceRepoUrl: "https://github.com/starchild-labs/ui-kit-generator",
    mcpServerUrl: null,
    skillFileUrl: "/agents/building/ui-kit-generator/SKILL.md",
    starCount: 1340,
    installCount: 3450,
    activeInstances: 567,
    configSchema: null,
    publisherId: pid(1),
  },
  {
    id: aid(11),
    slug: "funding-rate-arb",
    name: "Funding Rate Arb",
    description: "Monitors funding rate differentials across venues and executes delta-neutral arbitrage strategies on Orderly perps.",
    longDescription: null,
    division: "trading",
    runtime: "hosted" as const,
    riskLevel: "high" as const,
    status: "approved",
    iconEmoji: "💰",
    version: "0.9.0",
    tags: ["funding-rate", "arbitrage", "delta-neutral"],
    supportedChains: ["arbitrum"],
    brokerCompatibility: "all",
    sourceRepoUrl: null,
    mcpServerUrl: null,
    skillFileUrl: null,
    starCount: 512,
    installCount: 670,
    activeInstances: 0,
    configSchema: null,
    publisherId: pid(7),
  },
  {
    id: aid(12),
    slug: "community-dashboard",
    name: "Community Dashboard",
    description: "Auto-generates and maintains a community analytics dashboard showing trading volumes, user growth, and agent adoption metrics.",
    longDescription: null,
    division: "social",
    runtime: "skill" as const,
    riskLevel: "low" as const,
    status: "approved",
    iconEmoji: "📋",
    version: "1.2.0",
    tags: ["dashboard", "analytics", "community"],
    supportedChains: ["all"],
    brokerCompatibility: "all",
    sourceRepoUrl: "https://github.com/defi-dispatch/community-dashboard",
    mcpServerUrl: null,
    skillFileUrl: "/agents/social/community-dashboard/SKILL.md",
    starCount: 678,
    installCount: 1560,
    activeInstances: 234,
    configSchema: null,
    publisherId: pid(4),
  },
  {
    id: aid(13),
    slug: "smart-contract-auditor",
    name: "Smart Contract Auditor",
    description: "AI-powered static analysis for Solidity contracts integrating with Orderly. Catches common vulnerabilities and suggests gas optimizations.",
    longDescription: null,
    division: "building",
    runtime: "skill" as const,
    riskLevel: "low" as const,
    status: "approved",
    iconEmoji: "🔍",
    version: "1.0.3",
    tags: ["audit", "security", "solidity"],
    supportedChains: ["all"],
    brokerCompatibility: "all",
    sourceRepoUrl: "https://github.com/starchild-labs/contract-auditor",
    mcpServerUrl: null,
    skillFileUrl: "/agents/building/smart-contract-auditor/SKILL.md",
    starCount: 934,
    installCount: 2100,
    activeInstances: 345,
    configSchema: null,
    publisherId: pid(1),
  },
] as const;

export type MockAgent = (typeof mockAgents)[number];

function getPublisher(publisherId: string) {
  return mockPublishers.find((p) => p.id === publisherId)!;
}

export function getMockAgentCards() {
  return mockAgents.map((a) => {
    const pub = getPublisher(a.publisherId);
    return {
      id: a.id,
      slug: a.slug,
      name: a.name,
      description: a.description,
      division: a.division,
      runtime: a.runtime,
      riskLevel: a.riskLevel,
      iconEmoji: a.iconEmoji,
      tags: a.tags as unknown as string[],
      starCount: a.starCount,
      installCount: a.installCount,
      publisherName: pub.displayName,
      publisherSlug: pub.slug,
      publisherVerified: pub.isVerified,
    };
  });
}

export const mockTeams = [
  {
    id: tid(1),
    slug: "woofi-pro",
    displayName: "WOOFi Pro",
    tier: "diamond" as const,
    tagline: "Institutional-grade trading on WOO's flagship DEX",
    logoUrl: null,
    logoColor: "#1E40AF",
    memberCount: 12400,
    totalVolume: "2450000000",
    agentCount: 5,
    websiteUrl: "https://fi.woo.org",
    agents: [
      { id: aid(2), name: "Orderbook Analyst", slug: "orderbook-analyst", iconEmoji: "📊", runtime: "mcp" as const, description: "" },
      { id: aid(6), name: "Fee Optimizer", slug: "fee-optimizer", iconEmoji: "⚡", runtime: "skill" as const, description: "" },
      { id: aid(7), name: "WOO Liquidity Bridge", slug: "woo-liquidity-bridge", iconEmoji: "🌊", runtime: "mcp" as const, description: "" },
    ],
    roster: [
      { ...getMockAgentCards()[1], isFeatured: true, displayOrder: 1 },
      { ...getMockAgentCards()[5], isFeatured: true, displayOrder: 2 },
      { ...getMockAgentCards()[6], isFeatured: false, displayOrder: 3 },
      { ...getMockAgentCards()[4], isFeatured: false, displayOrder: 4 },
      { ...getMockAgentCards()[8], isFeatured: false, displayOrder: 5 },
    ],
  },
  {
    id: tid(2),
    slug: "logx-network",
    displayName: "LogX Network",
    tier: "platinum" as const,
    tagline: "Cross-chain perpetuals with AI-powered execution",
    logoUrl: null,
    logoColor: "#7C3AED",
    memberCount: 8900,
    totalVolume: "980000000",
    agentCount: 4,
    websiteUrl: "https://logx.trade",
    agents: [
      { id: aid(1), name: "Graduation Sniper", slug: "graduation-sniper", iconEmoji: "🎯", runtime: "skill" as const, description: "" },
      { id: aid(3), name: "DEX Vibe Coder", slug: "dex-vibe-coder", iconEmoji: "✨", runtime: "skill" as const, description: "" },
      { id: aid(9), name: "Alert Engine", slug: "alert-engine", iconEmoji: "🔔", runtime: "mcp" as const, description: "" },
    ],
    roster: [
      { ...getMockAgentCards()[0], isFeatured: true, displayOrder: 1 },
      { ...getMockAgentCards()[2], isFeatured: true, displayOrder: 2 },
      { ...getMockAgentCards()[8], isFeatured: false, displayOrder: 3 },
      { ...getMockAgentCards()[11], isFeatured: false, displayOrder: 4 },
    ],
  },
  {
    id: tid(3),
    slug: "elixir-dex",
    displayName: "Elixir DEX",
    tier: "gold" as const,
    tagline: "Community-first DEX with vibe-coded interfaces",
    logoUrl: null,
    logoColor: "#059669",
    memberCount: 5200,
    totalVolume: "340000000",
    agentCount: 3,
    websiteUrl: "https://elixir.finance",
    agents: [
      { id: aid(10), name: "UI Kit Generator", slug: "ui-kit-generator", iconEmoji: "🎨", runtime: "skill" as const, description: "" },
      { id: aid(5), name: "Social Sentinel", slug: "social-sentiment", iconEmoji: "📡", runtime: "mcp" as const, description: "" },
      { id: aid(12), name: "Community Dashboard", slug: "community-dashboard", iconEmoji: "📋", runtime: "skill" as const, description: "" },
    ],
    roster: [
      { ...getMockAgentCards()[9], isFeatured: true, displayOrder: 1 },
      { ...getMockAgentCards()[4], isFeatured: false, displayOrder: 2 },
      { ...getMockAgentCards()[11], isFeatured: false, displayOrder: 3 },
    ],
  },
];

export type MockTeam = (typeof mockTeams)[number];

export function getMockAgentDetail(slug: string) {
  const agent = mockAgents.find((a) => a.slug === slug);
  if (!agent) return null;

  const pub = getPublisher(agent.publisherId);
  const related = mockAgents
    .filter((a) => a.division === agent.division && a.id !== agent.id)
    .slice(0, 4);
  const teamsUsing = mockTeams
    .filter((t) => t.agents.some((a) => a.id === agent.id))
    .map((t) => ({
      teamId: t.id,
      teamName: t.displayName,
      teamSlug: t.slug,
      teamLogoColor: t.logoColor,
    }));

  return {
    ...agent,
    tags: agent.tags as unknown as string[],
    publisher: {
      id: pub.id,
      slug: pub.slug,
      displayName: pub.displayName,
      isVerified: pub.isVerified,
      isEcosystemPartner: pub.isEcosystemPartner,
      avatarUrl: pub.avatarUrl,
    },
    relatedAgents: related.map((r) => ({
      id: r.id,
      name: r.name,
      slug: r.slug,
      description: r.description,
      division: r.division,
      runtime: r.runtime,
      iconEmoji: r.iconEmoji,
      starCount: r.starCount,
    })),
    teamsUsing,
    isStarred: false,
  };
}

export function getMockPublisherDetail(slug: string) {
  const pub = mockPublishers.find((p) => p.slug === slug);
  if (!pub) return null;

  const pubAgents = mockAgents.filter((a) => a.publisherId === pub.id);
  const totalInstalls = pubAgents.reduce((s, a) => s + a.installCount, 0);
  const totalStars = pubAgents.reduce((s, a) => s + a.starCount, 0);

  return {
    ...pub,
    agentCount: pubAgents.length,
    totalInstalls,
    totalStars,
    agents: pubAgents.map((a) => ({
      id: a.id,
      slug: a.slug,
      name: a.name,
      description: a.description,
      division: a.division,
      runtime: a.runtime,
      riskLevel: a.riskLevel,
      iconEmoji: a.iconEmoji,
      tags: a.tags,
      starCount: a.starCount,
      installCount: a.installCount,
    })),
  };
}

export function getMockTeamDetail(slug: string) {
  return mockTeams.find((t) => t.slug === slug) ?? null;
}

export function getMockStats() {
  return {
    totalAgents: mockAgents.length,
    totalInstalls: mockAgents.reduce((s, a) => s + a.installCount, 0),
    activeTeams: mockTeams.length,
    contributors: mockPublishers.length,
  };
}
